##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: 0 0 * * *

jobs:
    CI:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install scons
                  sudo apt-get install valgrind
                  sudo apt-get install cppcheck
                  git submodule init
                  git submodule update

            - name: Static Code Analysis
              run: cppcheck src/ --std=c++17 --template=gcc --force --error-exitcode=1 -i src/plugins

            - name: Sanitize
              run: |
                  scons mode=debug+san
                  ./build/tests
                  ./build/tsunami_lab -v roe -s "shockshock 55 25" 500
                  scons mode=release+san
                  ./build/tests
                  ./build/tsunami_lab -v fwave 500

            - name: Valgrind
              run: |
                  scons mode=debug
                  valgrind ./build/tests
                  valgrind ./build/tsunami_lab -v roe 25

            - name: Release
              run: |
                  scons
                  ./build/tests
                  ./build/tsunami_lab -v fwave 500
