##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
    push:
        branches: [main, Test_OpenCL]
    pull_request:
        branches: [main]
    schedule:
        - cron: 0 0 * * *

jobs:
    CI:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install scons
                  sudo apt-get install libnetcdf-c++4-dev
                  sudo apt-get install netcdf-bin
                  sudo apt-get install valgrind
                  sudo apt-get install cppcheck
                  sudo apt install ocl-icd-opencl-dev
                  mkdir intel
                  cd intel
                  wget http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
                  tar zxvf opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
                  cd opencl_runtime_16.1.2_x64_rh_6.4.0.37
                  sudo ./install.sh -y
                  cd ../../
                  git submodule init
                  git submodule update
            #                 sudo apt-get install pocl-opencl-icd
            - name: Static Code Analysis
              run: cppcheck src/ --template=gcc --force --error-exitcode=1 --suppressions-list=cppcheck_suppress.txt

            - name: Sanitize 1D
              run: |
                  scons mode=debug+san
                  ./build/tests
                  ./build/tsunami_lab -d 1d -s "shockshock1d 55 25" 30
                  scons mode=release+san
                  ./build/tests
                  ./build/tsunami_lab -d 1d -s "tsunami1d" 30

            - name: Sanitize 2D
              run: |
                  scons mode=debug+san
                  ./build/tests
                  ./build/tsunami_lab -d 2d -s "dambreak2d" 30

            - name: Sanitize 2D
              run: |
                  scons mode=debug+san
                  ./build/tests
                  ./build/tsunami_lab -d 2d -s "dambreak2d" -o 1 30

            - name: Valgrind 1D
              run: |
                  scons mode=debug
                  valgrind ./build/tests
                  valgrind ./build/tsunami_lab -d 1d -s "dambreak1d 15 7" 25

            - name: Valgrind 2D
              run: |
                  scons mode=debug
                  valgrind ./build/tests
                  valgrind ./build/tsunami_lab -d 2d -s "dambreak2d" 25

            - name: Release
              run: |
                  scons
                  ./build/tests
                  ./build/tsunami_lab -d 2d -s "dambreak2d" 500
